baseURL = 'https://frogzone.neocities.org/'
languageCode = 'en-us'
title = 'will dowden . com'
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
MetaDataFormat = "toml"
uglyURLs = true
summaryLength = 10

[params]
site-creation-date = 2025-12-20

[security]
enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[indexes]
category = "categories"
tag = "tags"

[author]
name = "willy"

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'

[build]
writeStats = true

[build.processing.css]
enable = true
filetype = "scss"


[menus]
[[menus.main]]
name = 'home'
pageRef = '/'
weight = -1

[[menus.main]]
name = 'work'
pageRef = '/work/'
weight = 2

[[menus.main]]
name = "travels"
pageRef = '/travels/'
weight = 1